### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SoftwareMaven** [athoune/Erlang-Clamd#1]
Can you apply a license to this? I'm interested in using it (and perhaps contributing back), but my use is commercial so I need to know that I'm not violating term. Even if my use was non-commercial, I couldn't use this without a license.

**Comment by athoune** [comment]
ok. I'll put an MIT licence.

**Comment by athoune** [comment]
There is now a MIT licence.

**Comment by SoftwareMaven** [comment]
Thank you.
